version: "2"
services:
  postgres:
    image: unixelias/postgres-dspace:9.6-dev
    hostname: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  dspace:
    image: unixelias/docker-dspace:5.6-dev
    # If you wanto to change the configuration you can build again
    # and add custom config files
    #build: ./dspace
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB_HOST=postgres
      - POSTGRES_ADMIN_USER=postgres
      - POSTGRES_SCHEMA=dspace
      - POSTGRES_USER=dspace
      - POSTGRES_PASSWORD=password
    command: start-dspace

volumes:
  db_data:
